# Site Settings
site_name: Anelia
site_author: Anelia Stoyanova
docs_dir: docs 

copyright: © 2023 | Anelia Stoyanova

extra_css:
  - stylesheets/extra.css

# Material Configuration
theme:
  font:
    text: Manrope
  name: material
  custom_dir: overrides # Contains custom 'home.html' coverpage (and 'main.html')
  
  icon:
    logo: myicons/anelia-logo
  favicon: img/favicon.png  

  features:
    - navigation.indexes          # Implied section 'index.md' files
    - navigation.tabs             # Static upper section tabs (exist)
    - navigation.tabs.sticky      # Static upper section tabs (stay)
    - navigation.footer           # Add 'previous' and 'next' buttons in the footer
    - navigation.instant          # Keep navigation from reloading
    - navigation.instant.progress # Display page loading progress-bar ( > 400ms)
    - search.highlight            # Highlight all occurrences of queried string
    - search.share                # Search Query can be copied to Clipboard
    - search.suggest              # Display likeliest completion for the last queried word
    
  palette:
    # Light Mode
    - media: "(prefers-color-scheme: light)"
      scheme: lightanelia
      toggle:
        icon: material/weather-night
        name: Switch to Dark Mode

    # Dark Mode
    - media: "(prefers-color-scheme: dark)"
      scheme: darkanelia
      toggle:
        icon: material/weather-sunny
        name: Switch to Light Mode    
# nav:
#  - Section:
#   - section/index.md
#   - Page 1: section/index.md

plugins:
  - search
#  - roamlinks # Obsidian Style Image Support ![[<attachment_name>]]
  - blog
  - glightbox

# extra:
#  consent:
#    title: Cookie consent
#    description: >- 
#      We use cookies to recognize your repeated visits and preferences, as well
#      as to measure the effectiveness of our documentation and whether users
#      find what they're searching for. With your consent, you're helping us to
#      make our documentation better.

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons


extra:
  lists:
    - ['figma-logo.svg', 'affinity-logo.svg', 'miro-logo.svg', 'adobexd-logo.svg']
    - ['visual-studio-code-logo.svg', 'git-icon.svg', 'html5-logo.svg', 'css3-logo.svg', 'markdown-icon.svg']
    - ['jira-logo.svg', 'confluence-logo.svg', 'basecamp-logo.svg']

# Custom Homepage Elements
home_cover_image: img/glitch-landing.png # This path starts at your root mkdocs directory.
home_tagline: Designing with Heart ♥
home_description: Enhance your organization's digital product with a genuine blend of creativity, innovation, and a personal touch.
# Gradient Color


# Custom Homepage Button(s)
home_button1_name: Start now                     # Comment this parameter out to remove the button.
home_button1_url: section/                       # This path starts at your root mkdocs directory.
home_button1_theme: md-button md-button--primary # Options: "md-button", "md-button md-button--primary"

home_button2_name: Blog                             # Comment this parameter out to remove the button.
home_button2_url: blog/                             # This path starts at your root mkdocs directory.
home_button2_theme: md-button md-button--secondary  # Options: "md-button", "md-button md-button--primary"

home_button3_name: Clicky 3                         # Comment this parameter out to remove the button.
home_button3_url: Folder3/                          # This path starts at your root mkdocs directory.
home_button3_theme: md-button md-button--tertiary   # Options: "md-button", "md-button md-button--primary"

# Homepage Code Execution
home_execute_js: | # Javascript to execute when accessing the homepage
  console.log("This is an example!");